version: '3.8'

services:
  nest-sso:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4002:4000"
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      - nest-sso-db
      - nest-sso-redis
    environment:
      - NODE_ENV=development
  nest-sso-db:
    image: postgres:15
    restart: always
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
  nest-sso-redis:
    image: redis:7
    restart: always
    ports:
      - "6380:6379"

volumes:
  pgdata:
