version: '3.8'

services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4003:4000"
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - "6381:6379"

volumes:
  pgdata:
